repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3
      args: [-l119]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
